"""
html_exporter.py – Generates a downloadable comic-style HTML storyboard.
"""

import os
import pathlib


OUTPUTS_DIR = pathlib.Path(__file__).parent.parent.parent.parent.parent / "outputs"


def export_html_storyboard(panels: list, storyboard_id: str) -> str:
    """
    Build a self-contained HTML file and save to outputs/.
    Returns the relative path: outputs/storyboard_{id}.html
    """
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

    panels_html = ""
    for panel in panels:
        img_src = panel.get("image_url", "")
        title = panel.get("frame", {}).get("title", f"Scene {panel.get('scene_number','')}")
        caption = panel.get("caption", "")
        scene_text = panel.get("scene_text", "")
        num = panel.get("scene_number", "")

        panels_html += f"""
        <div class="panel">
            <div class="panel-number">Scene {num}</div>
            <img src="{img_src}" alt="{title}" loading="lazy"/>
            <div class="panel-content">
                <h2>{title}</h2>
                <p>{caption}</p>
                <details>
                    <summary>Scene Description</summary>
                    <p class="scene-text">{scene_text}</p>
                </details>
            </div>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Storyboard — {storyboard_id}</title>
<style>
  :root {{
    --bg: #0a0f1a;
    --surface: #151b2b;
    --teal: #00b4a6;
    --text: #f0f4f8;
    --muted: #a0aec0;
    --radius: 12px;
  }}
  *{{ box-sizing:border-box; margin:0; padding:0; }}
  body{{ background:var(--bg); color:var(--text); font-family:system-ui,sans-serif; padding:2rem; }}
  header{{ text-align:center; margin-bottom:2.5rem; }}
  header h1{{ font-size:2rem; color:var(--teal); }}
  header p{{ color:var(--muted); margin-top:.5rem; }}
  .grid{{
    display:grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap:1.5rem;
    max-width:1200px;
    margin:0 auto;
  }}
  .panel{{
    background:var(--surface);
    border-radius:var(--radius);
    overflow:hidden;
    border:1px solid rgba(0,180,166,.2);
    position:relative;
  }}
  .panel-number{{
    position:absolute; top:.8rem; left:.8rem;
    background:rgba(0,0,0,.7); color:#fff;
    padding:.25rem .75rem; border-radius:20px;
    font-size:.8rem; font-weight:600;
  }}
  .panel img{{ width:100%; aspect-ratio:16/9; object-fit:cover; display:block; }}
  .panel-content{{ padding:1.25rem; }}
  .panel-content h2{{ font-size:1rem; color:var(--teal); margin-bottom:.5rem; }}
  .panel-content p{{ font-size:.875rem; color:var(--muted); line-height:1.5; }}
  details{{ margin-top:.75rem; }}
  summary{{ cursor:pointer; font-size:.8rem; color:var(--teal); }}
  .scene-text{{ font-size:.8rem; color:var(--muted); margin-top:.5rem; }}
  footer{{ text-align:center; margin-top:3rem; color:var(--muted); font-size:.8rem; }}
</style>
</head>
<body>
<header>
  <h1>🎬 Pitch Visualizer Storyboard</h1>
  <p>ID: {storyboard_id}</p>
</header>
<div class="grid">
{panels_html}
</div>
<footer>Generated by Pitch Visualizer</footer>
</body>
</html>"""

    out_path = OUTPUTS_DIR / f"storyboard_{storyboard_id}.html"
    out_path.write_text(html, encoding="utf-8")
    return str(out_path)
